# This workflow is used to run pytest on the codebase

name: Pytest Workflow
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.10'
      
      - name: Create conda environment
        run: |
          conda env create -f _environment.yml
          conda activate eurovision-votes
  
      - name: Run tests
        run: |
          conda activate eurovision-votes
          pytest --maxfail=1 --disable-warnings -q tests 
          