# This workflow is used to run pytest on the codebase

name: Pytest Workflow
on: [push]

jobs:
  run-python-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: '3.12.10'
          environment-file: _environment.yml
          activate-environment: eurovision-votes
          auto-activate-base: false
      
  
      - name: Run tests with pytest
        shell: bash -l {0}
        run: |
          pytest -v --tb=auto tests/
          